[workspace]

resolver = "2"

members = [
    "maplibre",
    "maplibre-winit",
    "maplibre-build-tools",
    "maplibre-demo",

    "android",
    "apple",
    "web",

    "benchmarks",

    "experiments/wgpu_for_fontrendering"
]

[profile.release]
lto = true
codegen-units = 1
opt-level = 's'
panic = "abort"

strip = "debuginfo"

[profile.bench]
debug = true
