[package]
name = "maplibre-demo"
version = "0.1.0"
description = ""
categories = []
edition = "2021"

[features]
web-webgl = ["maplibre/web-webgl"]
enable-tracing = ["maplibre/enable-tracing", "tracing-subscriber", "tracing-tracy", "tracy-client"]

[dependencies]
env_logger = "0.9"
maplibre = { path = "../maplibre", version = "0.1.0"  }

tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", optional = true }
tracing-tracy = { version = "0.8", optional = true }
tracy-client = { version = "0.12.7", optional = true }