name: check
description: Check

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install toolchain
      shell: bash
      run: just default-toolchain
    - uses: Swatinem/rust-cache@v1
    - name: Format
      shell: bash
      run: just fmt-check
